### ISSUE TITLE
How to make Knit documentation to md, html, word and pdf files running on Windows 10

### ISSUE THREAD

**Issue by tgdbepe4** [grssnbchr/rddj-template#12]
There are several possibilities to Knit the documentation from a R Markdown file: md, html, pdf, and docx (MS Word) files. Mostly it's possible to create a md file but specially to pdf and MS Word files the process failed.

With the below described steps it should be possible to create all of that.

Software used:
**Windows 10 OS, V 1903, 64 bi**t
**RStudio, tested with Version 1.2.5001**
**R package "tidytex"**
 _Install it in RStudio!_
**MiKTeX 2.9**
**phantomjs-2.1.1-windows**
  _Place phantomjs-2.1.1-windows somewhere on the disk and add in the environment variable "Path" a new entry to the folder of the software, e.E. C:\phantomjs-2.1.1-windows\bin\__

In the R Markdown file on top:

Example:
"---
title: "My Project"
author: "Man on the Moon"
date: "January 1, 2050"
output:
  pdf_document:
    toc: yes
    toc_depth: '4'
  md_document: default
  html_document:
    code_folding: show
    echo: TRUE
    warning: FALSE
    message: FALSE
    theme: simplex
    df_print: default
    toc: yes
    toc_depth: 4
    toc_float: 
      collapsed: false
      smooth_scroll: false
  word_document:
    toc: yes
    toc_depth: '4'
---"

Check if in the "session" tab the "Set Working Directory" is set to the  correct. path.

Run the code and when no errors occurs click on the arrow on the right side of the "Knit" buttom above the R Markdown windows of RStudio and run the documentation process. First try "Knit to md_document". If this is working then next the "Knit to HTML", the "Knit to Word" and at the end "Knit to PDF. 

Hope you will have success as well. Please let me know your experience.

Any questions can be addressed to Peter Berger, mailto:Peter Berger@bergi-it-consulting.ch

**Comment by grssnbchr** [comment]
This will likely not work as expected with this template. The reason is that, when using the Knit button (whether to knit to PDF, HTML or whatsoever doesn't matter), *globally* installed R packages will be used. Instead, it should use *local* packages, i.e. packages installed through the `checkpoint` process. This is not trivial, and for this reason, the `knit.sh` script was implemented. So far, I've only implemented HTML knitting. PDF / Word etc. knitting would have to be implemented within `knit.sh` as well. Also, as `knit.sh` is a shell script, it so far only works on *Nix systems, and not on Windows (that is the actual reason for "knitting does not work on Windows").
